# Generated by Django 4.0.3 on 2022-04-28 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='videoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
        ),
    ]
