# Generated by Django 4.0.3 on 2022-04-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_subtitle_videoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoid',
            field=models.CharField(max_length=200),
        ),
    ]
