# Generated by Django 4.0.3 on 2022-04-28 17:29

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_videoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='streamer',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
