# Generated by Django 4.0.3 on 2022-05-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_streamer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='streamer',
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='start',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
