# Generated by Django 3.2.13 on 2022-05-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_rename_videoid_subtitle_video'),
        ('videos', '0005_remove_video_streamer_alter_subtitle_start_and_more'),
    ]

    operations = [
    ]
