# Generated by Django 4.0 on 2022-05-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_rename_video_subtitle_videoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='sub_num',
            field=models.IntegerField(default=1),
        ),
    ]
