# Generated by Django 4.0 on 2022-05-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_subtitle_sub_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='sub_num',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
