# Generated by Django 4.0.3 on 2022-03-29 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='longsummary',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_for_l', to='videos.video'),
        ),
        migrations.AddField(
            model_name='mediumsummary',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_for_m', to='videos.video'),
        ),
    ]
