# Generated by Django 4.0.3 on 2022-03-31 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        ('summary', '0002_longsummary_video_mediumsummary_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longsummary',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
        ),
        migrations.AlterField(
            model_name='mediumsummary',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
        ),
    ]
