# Generated by Django 4.0.4 on 2022-05-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_num',
            field=models.IntegerField(default=1),
        ),
    ]
